#sdk: "/Users/Ryota/.rvm/gems/ruby-1.9.3-p194@rhodes/gems/rhodes-3.3.3"
sdkversion: 3.3.3
name: geolocation
version: 1.0
vendor: rhomobile
build: debug
bbver: 4.6
applog: rholog.txt
iphone:
  configuration: Release
  sdk: iphonesimulator5.0
  provisionprofile:
  codesignidentity:
  entitlements:
  BundleIdentifier: com.rhomobile.geolocation
  BundleURLScheme: geolocation
wp:
  productid: 'dea118f0-bcd1-012f-250f-3c07542aa8a3'
symbian:
  uid: '0xedc5bf21'
android:
  version: 2.1
capabilities:
- gps
extensions: ["json", "another-extension"]
